//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affiliation
    {
        public int Id { get; set; }
        public Nullable<int> Business_Id { get; set; }
    
        public virtual Business Business { get; set; }
        public virtual MasterBusiness MasterBusiness { get; set; }
        public virtual Request Request { get; set; }
        public virtual BranchAffiliation BranchAffiliation { get; set; }
    }
}
