//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branches
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Branches()
        {
            this.BranchAffiliation = new HashSet<BranchAffiliation>();
            this.MID = new HashSet<MID>();
            this.TID = new HashSet<TID>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Business_Id { get; set; }
        public Nullable<int> AddFacility_Id { get; set; }
        public Nullable<System.Guid> Code { get; set; }
        public string BranchCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BranchAffiliation> BranchAffiliation { get; set; }
        public virtual Business Business { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MID> MID { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TID> TID { get; set; }
    }
}
