//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchAffiliation
    {
        public int Id { get; set; }
        public Nullable<int> Branch_Id { get; set; }
    
        public virtual Affiliation Affiliation { get; set; }
        public virtual Branches Branches { get; set; }
    }
}
