//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceMID
    {
        public int Id { get; set; }
        public Nullable<int> MonitorCode_Id { get; set; }
        public Nullable<int> CardPlans_Id { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public string MaintenanceMID1 { get; set; }
        public string MaintenanceMID11 { get; set; }
        public string MaintenanceMID12 { get; set; }
        public string MaintenanceMID13 { get; set; }
    
        public virtual FileMaintenance FileMaintenance { get; set; }
    }
}
