//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MID
    {
        public long Id { get; set; }
        public Nullable<int> MonitorCode_Id { get; set; }
        public Nullable<int> CardPlans_Id { get; set; }
        public string MID1 { get; set; }
        public Nullable<int> Branch_Id { get; set; }
        public string MID11 { get; set; }
        public string MID12 { get; set; }
        public string MID13 { get; set; }
    
        public virtual Branches Branches { get; set; }
    }
}
