//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAV2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MAP_DB_V2Entities : DbContext
    {
        public MAP_DB_V2Entities()
            : base("name=MAP_DB_V2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdditionalFacility> AdditionalFacility { get; set; }
        public virtual DbSet<Affiliation> Affiliation { get; set; }
        public virtual DbSet<Branches> Branches { get; set; }
        public virtual DbSet<Business> Business { get; set; }
        public virtual DbSet<FileMaintenance> FileMaintenance { get; set; }
        public virtual DbSet<MaintenanceMID> MaintenanceMID { get; set; }
        public virtual DbSet<MasterBranches> MasterBranches { get; set; }
        public virtual DbSet<MasterBusiness> MasterBusiness { get; set; }
        public virtual DbSet<MasterMaintenance> MasterMaintenance { get; set; }
        public virtual DbSet<MasterMID> MasterMID { get; set; }
        public virtual DbSet<MasterTID> MasterTID { get; set; }
        public virtual DbSet<MID> MID { get; set; }
        public virtual DbSet<POS> POS { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<TID> TID { get; set; }
        public virtual DbSet<AdditionalMID> AdditionalMID { get; set; }
        public virtual DbSet<BranchAffiliation> BranchAffiliation { get; set; }
        public virtual DbSet<DetailsMaintenance> DetailsMaintenance { get; set; }
        public virtual DbSet<MaintenanceFields> MaintenanceFields { get; set; }
    }
}
