//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Id { get; set; }
        public int RequestType { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string Createdby { get; set; }
    
        public virtual AdditionalFacility AdditionalFacility { get; set; }
        public virtual Affiliation Affiliation { get; set; }
        public virtual FileMaintenance FileMaintenance { get; set; }
        public virtual POS POS { get; set; }
    }
}
