//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TID
    {
        public int Id { get; set; }
        public Nullable<int> Branch_Id { get; set; }
        public string TID1 { get; set; }
        public string TID11 { get; set; }
        public string TID12 { get; set; }
        public string TID13 { get; set; }
    
        public virtual Branches Branches { get; set; }
    }
}
