//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAS_WorkFlowService.PaymentSolutions {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PaymentSolutions.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LoadRequestToPOSFlow", ReplyAction="http://tempuri.org/IService/LoadRequestToPOSFlowResponse")]
        MAS_WorkFlowService.PaymentSolutions.LoadRequestToPOSFlowResponse LoadRequestToPOSFlow(MAS_WorkFlowService.PaymentSolutions.LoadRequestToPOSFlowRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LoadRequestToPOSFlow", ReplyAction="http://tempuri.org/IService/LoadRequestToPOSFlowResponse")]
        System.Threading.Tasks.Task<MAS_WorkFlowService.PaymentSolutions.LoadRequestToPOSFlowResponse> LoadRequestToPOSFlowAsync(MAS_WorkFlowService.PaymentSolutions.LoadRequestToPOSFlowRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SubmitToPOSInventory", ReplyAction="http://tempuri.org/IService/SubmitToPOSInventoryResponse")]
        MAS_WorkFlowService.PaymentSolutions.SubmitToPOSInventoryResponse SubmitToPOSInventory(MAS_WorkFlowService.PaymentSolutions.SubmitToPOSInventoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SubmitToPOSInventory", ReplyAction="http://tempuri.org/IService/SubmitToPOSInventoryResponse")]
        System.Threading.Tasks.Task<MAS_WorkFlowService.PaymentSolutions.SubmitToPOSInventoryResponse> SubmitToPOSInventoryAsync(MAS_WorkFlowService.PaymentSolutions.SubmitToPOSInventoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CheckPOSInventory", ReplyAction="http://tempuri.org/IService/CheckPOSInventoryResponse")]
        MAS_WorkFlowService.PaymentSolutions.CheckPOSInventoryResponse CheckPOSInventory(MAS_WorkFlowService.PaymentSolutions.CheckPOSInventoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CheckPOSInventory", ReplyAction="http://tempuri.org/IService/CheckPOSInventoryResponse")]
        System.Threading.Tasks.Task<MAS_WorkFlowService.PaymentSolutions.CheckPOSInventoryResponse> CheckPOSInventoryAsync(MAS_WorkFlowService.PaymentSolutions.CheckPOSInventoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DonePOSPRofiling", ReplyAction="http://tempuri.org/IService/DonePOSPRofilingResponse")]
        MAS_WorkFlowService.PaymentSolutions.DonePOSPRofilingResponse DonePOSPRofiling(MAS_WorkFlowService.PaymentSolutions.DonePOSPRofilingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DonePOSPRofiling", ReplyAction="http://tempuri.org/IService/DonePOSPRofilingResponse")]
        System.Threading.Tasks.Task<MAS_WorkFlowService.PaymentSolutions.DonePOSPRofilingResponse> DonePOSPRofilingAsync(MAS_WorkFlowService.PaymentSolutions.DonePOSPRofilingRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadRequestToPOSFlow", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadRequestToPOSFlowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int paramPosRequestId;
        
        public LoadRequestToPOSFlowRequest() {
        }
        
        public LoadRequestToPOSFlowRequest(int paramPosRequestId) {
            this.paramPosRequestId = paramPosRequestId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadRequestToPOSFlowResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadRequestToPOSFlowResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string outMsg;
        
        public LoadRequestToPOSFlowResponse() {
        }
        
        public LoadRequestToPOSFlowResponse(string outMsg) {
            this.outMsg = outMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubmitToPOSInventory", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SubmitToPOSInventoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int paramPOSRequestId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public bool paramIsComplete;
        
        public SubmitToPOSInventoryRequest() {
        }
        
        public SubmitToPOSInventoryRequest(int paramPOSRequestId, bool paramIsComplete) {
            this.paramPOSRequestId = paramPOSRequestId;
            this.paramIsComplete = paramIsComplete;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubmitToPOSInventoryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SubmitToPOSInventoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string outMsg;
        
        public SubmitToPOSInventoryResponse() {
        }
        
        public SubmitToPOSInventoryResponse(string outMsg) {
            this.outMsg = outMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckPOSInventory", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CheckPOSInventoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int paramPosRequestId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public bool paramIsOk;
        
        public CheckPOSInventoryRequest() {
        }
        
        public CheckPOSInventoryRequest(int paramPosRequestId, bool paramIsOk) {
            this.paramPosRequestId = paramPosRequestId;
            this.paramIsOk = paramIsOk;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckPOSInventoryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CheckPOSInventoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string outMsg;
        
        public CheckPOSInventoryResponse() {
        }
        
        public CheckPOSInventoryResponse(string outMsg) {
            this.outMsg = outMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DonePOSPRofiling", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DonePOSPRofilingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int paramPOSRequestId;
        
        public DonePOSPRofilingRequest() {
        }
        
        public DonePOSPRofilingRequest(int paramPOSRequestId) {
            this.paramPOSRequestId = paramPOSRequestId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DonePOSPRofilingResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DonePOSPRofilingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string outMsg;
        
        public DonePOSPRofilingResponse() {
        }
        
        public DonePOSPRofilingResponse(string outMsg) {
            this.outMsg = outMsg;
        }
    }
}
